# Generated by Django 3.2.7 on 2021-09-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('evaluation', models.CharField(choices=[('A', 'Perfect'), ('B', 'Good'), ('C', 'Not Bad'), ('D', 'Failed')], help_text='Plan achievement evaluation', max_length=1)),
                ('start', models.DateTimeField(help_text='The start of the execution period of the plan')),
                ('end', models.DateTimeField(help_text='The end of the execution period of the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='User Primary Key', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(help_text='TimeTable Primary Key', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, max_length=500, null=True)),
                ('from_at', models.TimeField(help_text='The start time')),
                ('to_at', models.TimeField(help_text='The end time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='table.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='table.user'),
        ),
    ]
