# Generated by Django 3.2.7 on 2021-09-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('evaluation', models.CharField(blank=True, choices=[('A', 'Perfect'), ('B', 'Good'), ('C', 'Not Bad'), ('D', 'Failed')], help_text='Plan achievement evaluation', max_length=1, null=True)),
                ('start', models.DateTimeField(help_text='The start of the execution period of the plan')),
                ('end', models.DateTimeField(help_text='The end of the execution period of the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, max_length=500, null=True)),
                ('from_at', models.TimeField(help_text='The start time')),
                ('to_at', models.TimeField(help_text='The end time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth0authorization.plan')),
            ],
        ),
    ]
